import { type ServiceRecord, type BreakerSnapshot } from "./types";

export const HEARTBEATS = new Map<string, { lastSeen: number; lastError: string | null }>();
export const BREAKERS = new Map<string, BreakerSnapshot>();

export const SERVICE_DEFINITIONS: ServiceRecord[] = [
  {
    id: "supabase",
    name: "Supabase DB",
    status: "unknown",
    type: "db",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "redis",
    name: "Upstash Redis",
    status: "unknown",
    type: "db",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "gemini",
    name: "Gemini API",
    status: "unknown",
    type: "ai",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "anthropic",
    name: "Anthropic API",
    status: "unknown",
    type: "ai",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "openrouter",
    name: "OpenRouter Gateway",
    status: "unknown",
    type: "ai",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "resend",
    name: "Resend Email",
    status: "unknown",
    type: "api",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "sentry",
    name: "Sentry Monitoring",
    status: "unknown",
    type: "api",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "vercel",
    name: "Vercel Deploy",
    status: "unknown",
    type: "api",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-cost-alarm",
    name: "Cron: Cost Alarm",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-import-aiaaic",
    name: "Cron: Import AIAAIC",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-import-aiid",
    name: "Cron: Import AIID",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-generate-marketing",
    name: "Cron: Marketing",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-retro-audit",
    name: "Cron: Retro Audit",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-pivot-check",
    name: "Cron: Pivot Check",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-moderation-sla",
    name: "Cron: Moderation SLA",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "cron-newsletter",
    name: "Cron: Newsletter",
    status: "unknown",
    type: "cron",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "agent-autopilot",
    name: "Agent: Autopilot",
    status: "unknown",
    type: "agent",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "agent-marketing",
    name: "Agent: Marketing",
    status: "unknown",
    type: "agent",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "agent-sentinel",
    name: "Agent: Sentinel",
    status: "unknown",
    type: "agent",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "mcp-github",
    name: "MCP: GitHub",
    status: "unknown",
    type: "mcp",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "mcp-vercel",
    name: "MCP: Vercel",
    status: "unknown",
    type: "mcp",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "mcp-context7",
    name: "MCP: Context7",
    status: "unknown",
    type: "mcp",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
  {
    id: "mcp-playwright",
    name: "MCP: Playwright",
    status: "unknown",
    type: "mcp",
    lastHeartbeat: null,
    lastError: null,
    uptime: null,
    healthEndpoint: null,
  },
];
