import type { MetadataRoute } from "next";
import { APP_URL } from "@/lib/constants";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/en",
          "/tr",
          "/incidents",
          "/incidents/*",
          "/leaderboard",
          "/suggestions",
          "/suggestions/*",
          "/about",
          "/about/*",
          "/contact",
          "/blog",
          "/blog/*",
          "/press",
          "/press-kit",
          "/press-kit/*",
          "/pricing",
          "/pricing/*",
          "/products",
          "/products/*",
          "/trust-center",
          "/academy",
          "/academy/*",
          "/transparency",
          "/transparency/*",
          "/ai-act",
          "/compliance",
          "/compliance/*",
          "/compliance-checklist",
          "/constitution",
          "/experts",
          "/feed",
          "/invest",
          "/methodology",
          "/methodology/*",
          "/models",
          "/models/*",
          "/ratings",
          "/ratings/*",
          "/submit",
          "/submit/*",
          "/team",
          "/velocity",
          "/digital-twins",
          "/twins-leaderboard",
          "/vision",
          "/manifesto",
        ],
        disallow: [
          "/admin",
          "/admin/*",
          "/*/admin",
          "/*/admin/*",
          "/investor-portal",
          "/investor-portal/*",
          "/*/investor-portal",
          "/*/investor-portal/*",
          "/b2b/dashboard",
          "/*/b2b/dashboard",
          "/api/*",
          "/auth/*",
          "/*/auth/*",
          "/profile",
          "/*/profile",
          "/my-incidents",
          "/*/my-incidents",
          "/settings",
          "/*/settings",
          "/legal/takedown",
          "/*/legal/takedown",
        ],
      },
    ],
    sitemap: `${APP_URL}/sitemap.xml`,
    host: APP_URL,
  };
}
